<a href="https://colab.research.google.com/github/EvgeniaKantor/DI-Bootcamp_ML/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a1[5]

5

In [9]:
a1[3:8]

array([3, 4, 5, 6, 7])

In [12]:
# Create an array of 6 random integers between 10 and 50. Print the elements that are greater than 30.
a2 = np.random.randint(10, 50, 6)
a2

array([36, 35, 45, 41, 20, 15])

In [13]:
a2[a2 > 30]

array([36, 35, 45, 41])

In [15]:
a3 = np.arange(1, 11)
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a3[5] = 50
a3

array([ 1,  2,  3,  4,  5, 50,  7,  8,  9, 10])

In [18]:
a3[3:7] = -a3[3:7]
a3

array([  1,   2,   3,  -4,  -5, -50,  -7,   8,   9,  10])

In [20]:
a4 = np.random.randint(1,100,20)
a4

array([61,  2, 36, 87, 46, 86, 57, 45, 85, 45, 12, 23, 46, 34, 16, 72, 49,
       48, 44,  7])

In [23]:
a4[a4 > 50] = -1
a4

array([-1,  2, 36, -1, 46, -1, -1, 45, -1, 45, 12, 23, 46, 34, 16, -1, 49,
       48, 44,  7])

In [33]:
a5 = np.random.randint(1, 10, (5,5))
a5

array([[3, 6, 5, 2, 9],
       [2, 7, 4, 8, 4],
       [7, 5, 8, 2, 4],
       [3, 9, 6, 2, 6],
       [9, 2, 7, 6, 7]])

In [28]:
# Given a 2D array of shape (5, 5), modify the elements in the diagonal to be twice their original value.
a5 = np.arange(1, 26).reshape((5,5))
a5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
for i in range(5):
  for j in range(5):
    if i == j:
      a5[i, j] *= 2
print(a5)

[[ 2  4  6  3  6]
 [ 4  8  4  6  3]
 [ 9  7 10  6  8]
 [ 4  3  3  2  6]
 [ 2  4  4  4  6]]


In [29]:
for i in range(a5.shape[0]):
    a5[i, i] = 2 * a5[i, i]
print(a5)

[[ 2  2  3  4  5]
 [ 6 14  8  9 10]
 [11 12 26 14 15]
 [16 17 18 38 20]
 [21 22 23 24 50]]


In [36]:
a6 = np.arange(1, 11)
ar_slided = a6[2:5]
ar_slided[0]= 99
a6

array([ 1,  2, 99,  4,  5,  6,  7,  8,  9, 10])

In [37]:
a7 = np.random.randint(1, 10, (5,5))
a7

array([[8, 6, 6, 1, 4],
       [1, 6, 6, 4, 6],
       [2, 4, 6, 9, 7],
       [2, 6, 7, 8, 7],
       [1, 5, 9, 9, 4]])

In [38]:
for i in range(5):
  j = 4-i
  a7[i, j] = 0
print(a7)

[[8 6 6 1 0]
 [1 6 6 0 6]
 [2 4 0 9 7]
 [2 0 7 8 7]
 [0 5 9 9 4]]


In [42]:
a8 = np.random.randint(1, 12, 12)
a9 = a8.reshape(4,3)
a10 = a9.reshape(2,6)
a10

array([[10, 10, 10,  5, 10,  6],
       [ 5,  7,  6,  2, 11,  2]])

In [43]:
# Transpose the 2x6 matrix you created in the previous step.
a10.T

array([[10,  5],
       [10,  7],
       [10,  6],
       [ 5,  2],
       [10, 11],
       [ 6,  2]])

In [47]:
# Create a 3x4 matrix, transpose it, and then reshape the transposed matrix to a 1D array.
a11 = np.arange(1, 13).reshape(3,4)
a11.T
a11.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])