<a href="https://colab.research.google.com/github/EvgeniaKantor/DI-Bootcamp_ML/blob/main/xpW4D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 🌟 Exercise 1 : Array Creation and Manipulation

Instructions

Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 🌟 Exercise 2 : Type Conversion and Array Operations

Instructions

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:

array([3, 2, 0, 1, 2])

In [3]:
a2 = np.array([3.14, 2.17, 0, 1, 2])
a2 = a2.astype(int)
a2

array([3, 2, 0, 1, 2])

# 🌟 Exercise 3 : Working with Multi-Dimensional Arrays

Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a3 = np.arange(1, 10).reshape(3, 3)
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

Instructions

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:

array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [8]:
a4 = np.random.rand(4, 5)
a4 = np.round(a4, 2)
a4

array([[0.21, 0.19, 0.97, 0.71, 0.37],
       [0.82, 0.79, 0.81, 0.8 , 0.05],
       [0.  , 0.37, 0.22, 0.6 , 0.2 ],
       [0.21, 0.88, 0.17, 0.76, 0.88]])

# 🌟 Exercise 5 : Indexing Arrays

Instructions

Select the second row from a given 2D NumPy array.

Expected Output:

array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [9]:
a5 = np.array([[21, 22, 23, 22, 22],
                  [20, 21, 22, 23, 24],
                  [21, 22, 23, 22, 22]])
a5[1]

array([20, 21, 22, 23, 24])

# 🌟 Exercise 6 : Reversing elements

Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [11]:
a6 = a1[::-1]
a6

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 🌟 Exercise 7 : Identity Matrix

Instructions

Create a 4x4 identity matrix using NumPy.

Expected Output:

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
a7 = np.eye(4)
a7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 🌟 Exercise 8 : Simple Aggregate **Funcs**

Instructions

Find the sum and average of a given 1D array.

Expected Output:

Sum: 45, Average: 4.5

In [16]:
a8 = np.arange(10)
a8_sum = np.sum(a8)
a8_avg = np.average(a8)
print(f"Sum: {a8_sum}, Average: {a8_avg}")

Sum: 45, Average: 4.5


# 🌟 Exercise 9 : Create Array and Change its Structure

Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


In [17]:
a9 = np.arange(1, 21).reshape(4, 5)
a9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# 🌟 Exercise 10 : Conditional Selection of Values

Instructions

Extract all odd numbers from a given NumPy array.

Expected Output:

array([1, 3, 5, 7, 9])

In [21]:
a10 = np.arange(1,11)
a10 = a10[a10 % 2 == 1]
a10

array([1, 3, 5, 7, 9])